// Code generated by goyacc DO NOT EDIT.
// CAUTION: Generated file - DO NOT EDIT.

package parser

import __yyfmt__ "fmt"

import (
	"tinysql/parser/ast"
	"tinysql/parser/model"
	"tinysql/parser/opcode"
)

type yySymType struct {
	yys       int
	offset    int
	item      interface{}
	ident     string
	expr      ast.ExprNode
	statement ast.StmtNode
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault               = 57386
	yyEOFCode               = 57344
	Identifier              = 57380
	and                     = 57360
	andand                  = 57363
	as                      = 57348
	div                     = 57355
	eq                      = 57367
	yyErrCode               = 57345
	falseKwd                = 57358
	floatLit                = 57365
	from                    = 57347
	ge                      = 57368
	identifier              = 57376
	in                      = 57362
	inner                   = 57350
	intLit                  = 57366
	invalid                 = 57379
	is                      = 57361
	join                    = 57349
	le                      = 57369
	lowerThanSetKeyword     = 57382
	lowerThanStringLitToken = 57381
	lsh                     = 57370
	mod                     = 57356
	neg                     = 57385
	neq                     = 57371
	neqSynonym              = 57372
	not                     = 57353
	not2                    = 57375
	null                    = 57354
	nulleq                  = 57373
	or                      = 57359
	pipes                   = 57364
	pipesAsOr               = 57384
	rsh                     = 57374
	selectKwd               = 57346
	stringLit               = 57378
	tableRefPriority        = 57383
	trueKwd                 = 57357
	underscoreCS            = 57377
	where                   = 57351
	xor                     = 57352

	yyMaxDepth = 200
	yyTabOfs   = -92
)

var (
	yyXLAT = map[int]int{
		43:    0,  // '+' (70x)
		45:    1,  // '-' (70x)
		57344: 2,  // $end (67x)
		59:    3,  // ';' (66x)
		57380: 4,  // Identifier (55x)
		57360: 5,  // and (44x)
		57363: 6,  // andand (44x)
		57359: 7,  // or (44x)
		57384: 8,  // pipesAsOr (44x)
		57352: 9,  // xor (44x)
		41:    10, // ')' (43x)
		46:    11, // '.' (42x)
		57354: 12, // null (39x)
		57378: 13, // stringLit (39x)
		42:    14, // '*' (38x)
		60:    15, // '<' (38x)
		62:    16, // '>' (38x)
		57367: 17, // eq (38x)
		57368: 18, // ge (38x)
		57361: 19, // is (38x)
		57369: 20, // le (38x)
		57371: 21, // neq (38x)
		57372: 22, // neqSynonym (38x)
		57373: 23, // nulleq (38x)
		33:    24, // '!' (36x)
		40:    25, // '(' (36x)
		126:   26, // '~' (36x)
		57358: 27, // falseKwd (36x)
		57365: 28, // floatLit (36x)
		57366: 29, // intLit (36x)
		57375: 30, // not2 (36x)
		57357: 31, // trueKwd (36x)
		37:    32, // '%' (34x)
		38:    33, // '&' (34x)
		47:    34, // '/' (34x)
		94:    35, // '^' (34x)
		124:   36, // '|' (34x)
		57355: 37, // div (34x)
		57370: 38, // lsh (34x)
		57356: 39, // mod (34x)
		57374: 40, // rsh (34x)
		57398: 41, // Literal (24x)
		57404: 42, // SimpleExpr (24x)
		57405: 43, // SimpleIdent (24x)
		57409: 44, // StringLiteral (24x)
		44:    45, // ',' (21x)
		57387: 46, // BitExpr (19x)
		57351: 47, // where (16x)
		57349: 48, // join (13x)
		57350: 49, // inner (12x)
		125:   50, // '}' (11x)
		57353: 51, // not (11x)
		57347: 52, // from (8x)
		57399: 53, // PredicateExpr (7x)
		57388: 54, // BoolPri (6x)
		57392: 55, // Expression (6x)
		57419: 56, // logAnd (6x)
		57420: 57, // logOr (6x)
		57397: 58, // JoinTable (4x)
		57412: 59, // TableFactor (4x)
		57413: 60, // TableName (4x)
		57414: 61, // TableRef (4x)
		57348: 62, // as (3x)
		57390: 63, // CrossOpt (3x)
		123:   64, // '{' (2x)
		57391: 65, // EscapedTableRef (2x)
		57393: 66, // Field (2x)
		57346: 67, // selectKwd (2x)
		57400: 68, // SelectStmt (2x)
		57401: 69, // SelectStmtBasic (2x)
		57403: 70, // SelectStmtFromTable (2x)
		57407: 71, // Statement (2x)
		57389: 72, // CompareOp (1x)
		57394: 73, // FieldList (1x)
		57396: 74, // IsOrNotOp (1x)
		57402: 75, // SelectStmtFieldList (1x)
		57406: 76, // Start (1x)
		57408: 77, // StatementList (1x)
		57410: 78, // TableAsName (1x)
		57411: 79, // TableAsNameOpt (1x)
		57415: 80, // TableRefs (1x)
		57416: 81, // TableRefsClause (1x)
		57417: 82, // WhereClause (1x)
		57418: 83, // WhereClauseOptional (1x)
		57386: 84, // $default (0x)
		57345: 85, // error (0x)
		57376: 86, // identifier (0x)
		57362: 87, // in (0x)
		57395: 88, // InOrNotOp (0x)
		57379: 89, // invalid (0x)
		57382: 90, // lowerThanSetKeyword (0x)
		57381: 91, // lowerThanStringLitToken (0x)
		57385: 92, // neg (0x)
		57364: 93, // pipes (0x)
		57383: 94, // tableRefPriority (0x)
		57377: 95, // underscoreCS (0x)
	}

	yySymNames = []string{
		"'+'",
		"'-'",
		"$end",
		"';'",
		"Identifier",
		"and",
		"andand",
		"or",
		"pipesAsOr",
		"xor",
		"')'",
		"'.'",
		"null",
		"stringLit",
		"'*'",
		"'<'",
		"'>'",
		"eq",
		"ge",
		"is",
		"le",
		"neq",
		"neqSynonym",
		"nulleq",
		"'!'",
		"'('",
		"'~'",
		"falseKwd",
		"floatLit",
		"intLit",
		"not2",
		"trueKwd",
		"'%'",
		"'&'",
		"'/'",
		"'^'",
		"'|'",
		"div",
		"lsh",
		"mod",
		"rsh",
		"Literal",
		"SimpleExpr",
		"SimpleIdent",
		"StringLiteral",
		"','",
		"BitExpr",
		"where",
		"join",
		"inner",
		"'}'",
		"not",
		"from",
		"PredicateExpr",
		"BoolPri",
		"Expression",
		"logAnd",
		"logOr",
		"JoinTable",
		"TableFactor",
		"TableName",
		"TableRef",
		"as",
		"CrossOpt",
		"'{'",
		"EscapedTableRef",
		"Field",
		"selectKwd",
		"SelectStmt",
		"SelectStmtBasic",
		"SelectStmtFromTable",
		"Statement",
		"CompareOp",
		"FieldList",
		"IsOrNotOp",
		"SelectStmtFieldList",
		"Start",
		"StatementList",
		"TableAsName",
		"TableAsNameOpt",
		"TableRefs",
		"TableRefsClause",
		"WhereClause",
		"WhereClauseOptional",
		"$default",
		"error",
		"identifier",
		"in",
		"InOrNotOp",
		"invalid",
		"lowerThanSetKeyword",
		"lowerThanStringLitToken",
		"neg",
		"pipes",
		"tableRefPriority",
		"underscoreCS",
	}

	yyReductions = []struct{ xsym, components int }{
		{0, 1},
		{76, 1},
		{77, 1},
		{77, 3},
		{71, 1},
		{68, 1},
		{70, 4},
		{69, 2},
		{75, 1},
		{73, 1},
		{73, 3},
		{66, 1},
		{66, 3},
		{66, 5},
		{81, 1},
		{80, 1},
		{80, 3},
		{65, 1},
		{65, 4},
		{61, 1},
		{61, 1},
		{59, 2},
		{60, 1},
		{60, 3},
		{79, 0},
		{79, 1},
		{78, 1},
		{78, 2},
		{58, 3},
		{63, 1},
		{63, 2},
		{83, 0},
		{83, 1},
		{82, 2},
		{55, 3},
		{55, 3},
		{55, 3},
		{55, 2},
		{55, 1},
		{54, 3},
		{54, 3},
		{54, 1},
		{53, 1},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 3},
		{46, 1},
		{42, 1},
		{42, 1},
		{42, 2},
		{42, 2},
		{42, 2},
		{42, 2},
		{42, 2},
		{42, 3},
		{43, 1},
		{43, 3},
		{43, 4},
		{43, 5},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{41, 1},
		{44, 1},
		{44, 2},
		{57, 1},
		{57, 1},
		{56, 1},
		{56, 1},
		{74, 1},
		{74, 2},
		{88, 1},
		{88, 2},
		{72, 1},
		{72, 1},
		{72, 1},
		{72, 1},
		{72, 1},
		{72, 1},
		{72, 1},
		{72, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [139][]uint16{
		// 0
		{67: 99, 96, 98, 97, 95, 76: 93, 94},
		{2: 92},
		{2: 91, 229},
		{2: 90, 90},
		{2: 88, 88},
		// 5
		{2: 87, 87},
		{52: 112},
		{4: 104, 14: 103, 66: 102, 73: 101, 75: 100},
		{52: 85},
		{45: 110, 52: 84},
		// 10
		{45: 83, 52: 83},
		{45: 81, 52: 81},
		{11: 105},
		{4: 107, 14: 106},
		{45: 80, 52: 80},
		// 15
		{11: 108},
		{14: 109},
		{45: 79, 52: 79},
		{4: 104, 14: 103, 66: 111},
		{45: 82, 52: 82},
		// 20
		{4: 121, 58: 119, 118, 120, 116, 64: 117, 115, 80: 114, 113},
		{2: 61, 61, 47: 141, 82: 140, 139},
		{2: 78, 78, 45: 137, 47: 78},
		{2: 77, 77, 45: 77, 47: 77},
		{2: 75, 75, 45: 75, 47: 75, 133, 134, 63: 132},
		// 25
		{4: 129},
		{2: 73, 73, 45: 73, 47: 73, 73, 73, 73},
		{2: 72, 72, 45: 72, 47: 72, 72, 72, 72},
		{2: 68, 68, 126, 45: 68, 47: 68, 68, 68, 68, 62: 127, 78: 125, 124},
		{2: 70, 70, 70, 11: 122, 45: 70, 47: 70, 70, 70, 70, 62: 70},
		// 30
		{4: 123},
		{2: 69, 69, 69, 45: 69, 47: 69, 69, 69, 69, 62: 69},
		{2: 71, 71, 45: 71, 47: 71, 71, 71, 71},
		{2: 67, 67, 45: 67, 47: 67, 67, 67, 67},
		{2: 66, 66, 45: 66, 47: 66, 66, 66, 66},
		// 35
		{4: 128},
		{2: 65, 65, 45: 65, 47: 65, 65, 65, 65},
		{4: 121, 58: 119, 118, 120, 130},
		{48: 133, 134, 131, 63: 132},
		{2: 74, 74, 45: 74, 47: 74},
		// 40
		{4: 121, 58: 119, 118, 120, 136},
		{4: 63},
		{48: 135},
		{4: 62},
		{2: 64, 64, 45: 64, 47: 64, 64, 64, 64, 63: 132},
		// 45
		{4: 121, 58: 119, 118, 120, 116, 64: 117, 138},
		{2: 76, 76, 45: 76, 47: 76},
		{2: 86, 86},
		{2: 60, 60},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 146, 51: 143, 53: 145, 144, 142},
		// 50
		{2: 59, 59, 5: 181, 180, 179, 178, 175, 56: 176, 174},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 146, 51: 143, 53: 145, 144, 228},
		{2: 54, 54, 5: 54, 54, 54, 54, 54, 54, 15: 220, 218, 223, 217, 216, 219, 221, 222, 224, 72: 215, 74: 214},
		{2: 51, 51, 5: 51, 51, 51, 51, 51, 51, 15: 51, 51, 51, 51, 51, 51, 51, 51, 51},
		{194, 195, 50, 50, 5: 50, 50, 50, 50, 50, 50, 14: 196, 50, 50, 50, 50, 50, 50, 50, 50, 50, 32: 198, 191, 197, 201, 190, 199, 192, 200, 193},
		// 55
		{37, 37, 37, 37, 5: 37, 37, 37, 37, 37, 37, 14: 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 32: 37, 37, 37, 37, 37, 37, 37, 37, 37},
		{36, 36, 36, 36, 5: 36, 36, 36, 36, 36, 36, 14: 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 32: 36, 36, 36, 36, 36, 36, 36, 36, 36},
		{35, 35, 35, 35, 5: 35, 35, 35, 35, 35, 35, 14: 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 32: 35, 35, 35, 35, 35, 35, 35, 35, 35},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 189, 148, 163},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 188, 148, 163},
		// 60
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 187, 148, 163},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 186, 148, 163},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 185, 148, 163},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 146, 51: 143, 53: 145, 144, 173},
		{28, 28, 28, 28, 5: 28, 28, 28, 28, 28, 28, 169, 14: 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 32: 28, 28, 28, 28, 28, 28, 28, 28, 28},
		// 65
		{4: 166},
		{24, 24, 24, 24, 5: 24, 24, 24, 24, 24, 24, 14: 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 32: 24, 24, 24, 24, 24, 24, 24, 24, 24},
		{23, 23, 23, 23, 5: 23, 23, 23, 23, 23, 23, 14: 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 32: 23, 23, 23, 23, 23, 23, 23, 23, 23},
		{22, 22, 22, 22, 5: 22, 22, 22, 22, 22, 22, 14: 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 32: 22, 22, 22, 22, 22, 22, 22, 22, 22},
		{21, 21, 21, 21, 5: 21, 21, 21, 21, 21, 21, 14: 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 32: 21, 21, 21, 21, 21, 21, 21, 21, 21},
		// 70
		{20, 20, 20, 20, 5: 20, 20, 20, 20, 20, 20, 14: 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 32: 20, 20, 20, 20, 20, 20, 20, 20, 20},
		{19, 19, 19, 19, 5: 19, 19, 19, 19, 19, 19, 13: 165, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 32: 19, 19, 19, 19, 19, 19, 19, 19, 19},
		{18, 18, 18, 18, 5: 18, 18, 18, 18, 18, 18, 13: 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 32: 18, 18, 18, 18, 18, 18, 18, 18, 18},
		{17, 17, 17, 17, 5: 17, 17, 17, 17, 17, 17, 13: 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 32: 17, 17, 17, 17, 17, 17, 17, 17, 17},
		{11: 167},
		// 75
		{4: 168},
		{26, 26, 26, 26, 5: 26, 26, 26, 26, 26, 26, 14: 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 32: 26, 26, 26, 26, 26, 26, 26, 26, 26},
		{4: 170},
		{27, 27, 27, 27, 5: 27, 27, 27, 27, 27, 27, 171, 14: 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 32: 27, 27, 27, 27, 27, 27, 27, 27, 27},
		{4: 172},
		// 80
		{25, 25, 25, 25, 5: 25, 25, 25, 25, 25, 25, 14: 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 32: 25, 25, 25, 25, 25, 25, 25, 25, 25},
		{5: 181, 180, 179, 178, 175, 177, 56: 176, 174},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 146, 51: 143, 53: 145, 144, 184},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 146, 51: 143, 53: 145, 144, 183},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 146, 51: 143, 53: 145, 144, 182},
		// 85
		{29, 29, 29, 29, 5: 29, 29, 29, 29, 29, 29, 14: 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 32: 29, 29, 29, 29, 29, 29, 29, 29, 29},
		{16, 16, 4: 16, 11: 16, 16, 16, 24: 16, 16, 16, 16, 16, 16, 16, 16, 51: 16},
		{15, 15, 4: 15, 11: 15, 15, 15, 24: 15, 15, 15, 15, 15, 15, 15, 15, 51: 15},
		{14, 14, 4: 14, 11: 14, 14, 14, 24: 14, 14, 14, 14, 14, 14, 14, 14, 51: 14},
		{13, 13, 4: 13, 11: 13, 13, 13, 24: 13, 13, 13, 13, 13, 13, 13, 13, 51: 13},
		// 90
		{2: 56, 56, 5: 56, 56, 56, 56, 56, 56, 56: 176, 174},
		{2: 57, 57, 5: 181, 180, 57, 57, 57, 57, 56: 176, 174},
		{2: 58, 58, 5: 181, 180, 58, 58, 175, 58, 56: 176, 174},
		{30, 30, 30, 30, 5: 30, 30, 30, 30, 30, 30, 14: 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 32: 30, 30, 30, 30, 30, 30, 30, 30, 30},
		{31, 31, 31, 31, 5: 31, 31, 31, 31, 31, 31, 14: 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32: 31, 31, 31, 31, 31, 31, 31, 31, 31},
		// 95
		{32, 32, 32, 32, 5: 32, 32, 32, 32, 32, 32, 14: 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32: 32, 32, 32, 32, 32, 32, 32, 32, 32},
		{33, 33, 33, 33, 5: 33, 33, 33, 33, 33, 33, 14: 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 32: 33, 33, 33, 33, 33, 33, 33, 33, 33},
		{34, 34, 34, 34, 5: 34, 34, 34, 34, 34, 34, 14: 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 32: 34, 34, 34, 34, 34, 34, 34, 34, 34},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 213},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 212},
		// 100
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 211},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 210},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 209},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 208},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 207},
		// 105
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 206},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 205},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 204},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 203},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 202},
		// 110
		{38, 38, 38, 38, 5: 38, 38, 38, 38, 38, 38, 14: 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 32: 38, 38, 38, 38, 38, 38, 38, 38, 38},
		{39, 39, 39, 39, 5: 39, 39, 39, 39, 39, 39, 14: 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 32: 39, 39, 39, 201, 39, 39, 39, 39, 39},
		{40, 40, 40, 40, 5: 40, 40, 40, 40, 40, 40, 14: 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 32: 40, 40, 40, 201, 40, 40, 40, 40, 40},
		{41, 41, 41, 41, 5: 41, 41, 41, 41, 41, 41, 14: 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 32: 41, 41, 41, 201, 41, 41, 41, 41, 41},
		{42, 42, 42, 42, 5: 42, 42, 42, 42, 42, 42, 14: 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 32: 42, 42, 42, 201, 42, 42, 42, 42, 42},
		// 115
		{43, 43, 43, 43, 5: 43, 43, 43, 43, 43, 43, 14: 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 32: 43, 43, 43, 201, 43, 43, 43, 43, 43},
		{44, 44, 44, 44, 5: 44, 44, 44, 44, 44, 44, 14: 196, 44, 44, 44, 44, 44, 44, 44, 44, 44, 32: 198, 44, 197, 201, 44, 199, 44, 200, 44},
		{45, 45, 45, 45, 5: 45, 45, 45, 45, 45, 45, 14: 196, 45, 45, 45, 45, 45, 45, 45, 45, 45, 32: 198, 45, 197, 201, 45, 199, 45, 200, 45},
		{194, 195, 46, 46, 5: 46, 46, 46, 46, 46, 46, 14: 196, 46, 46, 46, 46, 46, 46, 46, 46, 46, 32: 198, 46, 197, 201, 46, 199, 46, 200, 46},
		{194, 195, 47, 47, 5: 47, 47, 47, 47, 47, 47, 14: 196, 47, 47, 47, 47, 47, 47, 47, 47, 47, 32: 198, 47, 197, 201, 47, 199, 47, 200, 47},
		// 120
		{194, 195, 48, 48, 5: 48, 48, 48, 48, 48, 48, 14: 196, 48, 48, 48, 48, 48, 48, 48, 48, 48, 32: 198, 48, 197, 201, 48, 199, 192, 200, 193},
		{194, 195, 49, 49, 5: 49, 49, 49, 49, 49, 49, 14: 196, 49, 49, 49, 49, 49, 49, 49, 49, 49, 32: 198, 191, 197, 201, 49, 199, 192, 200, 193},
		{12: 227},
		{153, 152, 4: 156, 11: 157, 159, 164, 24: 150, 155, 151, 158, 161, 162, 154, 160, 41: 149, 147, 148, 163, 46: 146, 53: 226},
		{12: 12, 51: 225},
		// 125
		{8, 8, 4: 8, 11: 8, 8, 8, 24: 8, 8, 8, 8, 8, 8, 8, 8},
		{7, 7, 4: 7, 11: 7, 7, 7, 24: 7, 7, 7, 7, 7, 7, 7, 7},
		{6, 6, 4: 6, 11: 6, 6, 6, 24: 6, 6, 6, 6, 6, 6, 6, 6},
		{5, 5, 4: 5, 11: 5, 5, 5, 24: 5, 5, 5, 5, 5, 5, 5, 5},
		{4, 4, 4: 4, 11: 4, 4, 4, 24: 4, 4, 4, 4, 4, 4, 4, 4},
		// 130
		{3, 3, 4: 3, 11: 3, 3, 3, 24: 3, 3, 3, 3, 3, 3, 3, 3},
		{2, 2, 4: 2, 11: 2, 2, 2, 24: 2, 2, 2, 2, 2, 2, 2, 2},
		{1, 1, 4: 1, 11: 1, 1, 1, 24: 1, 1, 1, 1, 1, 1, 1, 1},
		{12: 11},
		{2: 52, 52, 5: 52, 52, 52, 52, 52, 52, 15: 52, 52, 52, 52, 52, 52, 52, 52, 52},
		// 135
		{2: 53, 53, 5: 53, 53, 53, 53, 53, 53, 15: 53, 53, 53, 53, 53, 53, 53, 53, 53},
		{2: 55, 55, 5: 55, 55, 55, 55, 55, 55, 56: 176, 174},
		{67: 99, 96, 98, 97, 230},
		{2: 89, 89},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Errorf(format string, a ...interface{}) error
	AppendError(err error)
	Errors() (warns []error, errs []error)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEOFCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer, parser *Parser) int {
	const yyError = 85

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	parser.yylval = yySymType{}
	yyS := parser.cache

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
		parser.cache = yyS
	}
	parser.yyVAL = &yyS[yyp+1]
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yychar = yylex1(yylex, &parser.yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		*parser.yyVAL = parser.yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if !ok || msg == "" {
				msg = "syntax error"
			}
			// ignore goyacc error message
			yylex.AppendError(yylex.Errorf(""))
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEOFCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
		parser.cache = yyS
	}
	parser.yyVAL = &yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 2:
		{
			if yyS[yypt-0].statement != nil {
				s := yyS[yypt-0].statement
				if lexer, ok := yylex.(stmtTexter); ok {
					s.SetText(lexer.stmtText())
				}
				parser.result = append(parser.result, s)
			}
		}
	case 3:
		{
			if yyS[yypt-0].statement != nil {
				s := yyS[yypt-0].statement
				if lexer, ok := yylex.(stmtTexter); ok {
					s.SetText(lexer.stmtText())
				}
				parser.result = append(parser.result, s)
			}
		}
	case 5:
		{
			st := yyS[yypt-0].item.(*ast.SelectStmt)
			parser.yyVAL.statement = st
		}
	case 6:
		{
			st := yyS[yypt-3].item.(*ast.SelectStmt)
			st.From = yyS[yypt-1].item.(*ast.TableRefsClause)
			lastField := st.Fields.Fields[len(st.Fields.Fields)-1]
			if lastField.Expr != nil && lastField.AsName.O == "" {
				lastEnd := parser.endOffset(&yyS[yypt-4])
				lastField.SetText(parser.src[lastField.Offset:lastEnd])
			}
			if yyS[yypt-0].item != nil {
				st.Where = yyS[yypt-0].item.(ast.ExprNode)
			}
			parser.yyVAL.item = st
		}
	case 7:
		{
			st := &ast.SelectStmt{
				Fields: yyS[yypt-0].item.(*ast.FieldList),
			}
			parser.yyVAL.item = st
		}
	case 8:
		{
			parser.yyVAL.item = &ast.FieldList{Fields: yyS[yypt-0].item.([]*ast.SelectField)}
		}
	case 9:
		{
			field := yyS[yypt-0].item.(*ast.SelectField)
			field.Offset = parser.startOffset(&yyS[yypt])
			parser.yyVAL.item = []*ast.SelectField{field}
		}
	case 10:
		{

			fl := yyS[yypt-2].item.([]*ast.SelectField)
			last := fl[len(fl)-1]
			if last.Expr != nil && last.AsName.O == "" {
				lastEnd := parser.endOffset(&yyS[yypt-1])
				last.SetText(parser.src[last.Offset:lastEnd])
			}
			newField := yyS[yypt-0].item.(*ast.SelectField)
			newField.Offset = parser.startOffset(&yyS[yypt])
			parser.yyVAL.item = append(fl, newField)
		}
	case 11:
		{
			parser.yyVAL.item = &ast.SelectField{WildCard: &ast.WildCardField{}}
		}
	case 12:
		{
			wildCard := &ast.WildCardField{Table: model.NewCIStr(yyS[yypt-2].ident)}
			parser.yyVAL.item = &ast.SelectField{WildCard: wildCard}
		}
	case 13:
		{
			wildCard := &ast.WildCardField{Schema: model.NewCIStr(yyS[yypt-4].ident), Table: model.NewCIStr(yyS[yypt-2].ident)}
			parser.yyVAL.item = &ast.SelectField{WildCard: wildCard}
		}
	case 14:
		{
			parser.yyVAL.item = &ast.TableRefsClause{TableRefs: yyS[yypt-0].item.(*ast.Join)}
		}
	case 15:
		{
			if j, ok := yyS[yypt-0].item.(*ast.Join); ok {
				// if $1 is Join, use it directly
				parser.yyVAL.item = j
			} else {
				parser.yyVAL.item = &ast.Join{Left: yyS[yypt-0].item.(ast.ResultSetNode), Right: nil}
			}
		}
	case 16:
		{
			/* from a, b is default cross join */
			parser.yyVAL.item = &ast.Join{Left: yyS[yypt-2].item.(ast.ResultSetNode), Right: yyS[yypt-0].item.(ast.ResultSetNode), Tp: ast.CrossJoin}
		}
	case 17:
		{
			parser.yyVAL.item = yyS[yypt-0].item
		}
	case 18:
		{
			/*
			* ODBC escape syntax for outer join is { OJ join_table }
			* Use an Identifier for OJ
			 */
			parser.yyVAL.item = yyS[yypt-1].item
		}
	case 19:
		{
			parser.yyVAL.item = yyS[yypt-0].item
		}
	case 20:
		{
			parser.yyVAL.item = yyS[yypt-0].item
		}
	case 21:
		{
			tn := yyS[yypt-1].item.(*ast.TableName)
			parser.yyVAL.item = &ast.TableSource{Source: tn, AsName: yyS[yypt-0].item.(model.CIStr)}
		}
	case 22:
		{
			parser.yyVAL.item = &ast.TableName{Name: model.NewCIStr(yyS[yypt-0].ident)}
		}
	case 23:
		{
			parser.yyVAL.item = &ast.TableName{Schema: model.NewCIStr(yyS[yypt-2].ident), Name: model.NewCIStr(yyS[yypt-0].ident)}
		}
	case 24:
		{
			parser.yyVAL.item = model.CIStr{}
		}
	case 25:
		{
			parser.yyVAL.item = yyS[yypt-0].item
		}
	case 26:
		{
			parser.yyVAL.item = model.NewCIStr(yyS[yypt-0].ident)
		}
	case 27:
		{
			parser.yyVAL.item = model.NewCIStr(yyS[yypt-0].ident)
		}
	case 28:
		{
			parser.yyVAL.item = &ast.Join{Left: yyS[yypt-2].item.(ast.ResultSetNode), Right: yyS[yypt-0].item.(ast.ResultSetNode), Tp: ast.CrossJoin}
		}
	case 31:
		{
			parser.yyVAL.item = nil
		}
	case 32:
		{
			parser.yyVAL.item = yyS[yypt-0].item
		}
	case 33:
		{
			parser.yyVAL.item = yyS[yypt-0].expr
		}
	case 34:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.LogicOr, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 35:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.LogicXor, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 36:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.LogicAnd, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 37:
		{
			parser.yyVAL.expr = &ast.UnaryOperationExpr{Op: opcode.Not, V: yyS[yypt-0].expr}
		}
	case 39:
		{
			parser.yyVAL.expr = &ast.IsNullExpr{Expr: yyS[yypt-2].expr, Not: !yyS[yypt-1].item.(bool)}
		}
	case 40:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: yyS[yypt-1].item.(opcode.Op), L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 43:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Or, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 44:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.And, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 45:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.LeftShift, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 46:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.RightShift, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 47:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Plus, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 48:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Minus, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 49:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Mul, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 50:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Div, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 51:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Mod, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 52:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.IntDiv, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 53:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Mod, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 54:
		{
			parser.yyVAL.expr = &ast.BinaryOperationExpr{Op: opcode.Xor, L: yyS[yypt-2].expr, R: yyS[yypt-0].expr}
		}
	case 58:
		{
			parser.yyVAL.expr = &ast.UnaryOperationExpr{Op: opcode.Not, V: yyS[yypt-0].expr}
		}
	case 59:
		{
			parser.yyVAL.expr = &ast.UnaryOperationExpr{Op: opcode.BitNeg, V: yyS[yypt-0].expr}
		}
	case 60:
		{
			parser.yyVAL.expr = &ast.UnaryOperationExpr{Op: opcode.Minus, V: yyS[yypt-0].expr}
		}
	case 61:
		{
			parser.yyVAL.expr = &ast.UnaryOperationExpr{Op: opcode.Plus, V: yyS[yypt-0].expr}
		}
	case 62:
		{
			parser.yyVAL.expr = &ast.UnaryOperationExpr{Op: opcode.Not, V: yyS[yypt-0].expr}
		}
	case 63:
		{
			startOffset := parser.startOffset(&yyS[yypt-1])
			endOffset := parser.endOffset(&yyS[yypt])
			expr := yyS[yypt-1].expr
			expr.SetText(parser.src[startOffset:endOffset])
			parser.yyVAL.expr = &ast.ParenthesesExpr{Expr: expr}
		}
	case 64:
		{
			parser.yyVAL.expr = &ast.ColumnNameExpr{Name: &ast.ColumnName{
				Name: model.NewCIStr(yyS[yypt-0].ident),
			}}
		}
	case 65:
		{
			parser.yyVAL.expr = &ast.ColumnNameExpr{Name: &ast.ColumnName{
				Table: model.NewCIStr(yyS[yypt-2].ident),
				Name:  model.NewCIStr(yyS[yypt-0].ident),
			}}
		}
	case 66:
		{
			parser.yyVAL.expr = &ast.ColumnNameExpr{Name: &ast.ColumnName{
				Table: model.NewCIStr(yyS[yypt-2].ident),
				Name:  model.NewCIStr(yyS[yypt-0].ident),
			}}
		}
	case 67:
		{
			parser.yyVAL.expr = &ast.ColumnNameExpr{Name: &ast.ColumnName{
				Schema: model.NewCIStr(yyS[yypt-4].ident),
				Table:  model.NewCIStr(yyS[yypt-2].ident),
				Name:   model.NewCIStr(yyS[yypt-0].ident),
			}}
		}
	case 68:
		{
			parser.yyVAL.expr = ast.NewValueExpr(false)
		}
	case 69:
		{
			parser.yyVAL.expr = ast.NewValueExpr(nil)
		}
	case 70:
		{
			parser.yyVAL.expr = ast.NewValueExpr(true)
		}
	case 71:
		{
			parser.yyVAL.expr = ast.NewValueExpr(yyS[yypt-0].item)
		}
	case 72:
		{
			parser.yyVAL.expr = ast.NewValueExpr(yyS[yypt-0].item)
		}
	case 73:
		{
			parser.yyVAL.expr = yyS[yypt-0].expr
		}
	case 74:
		{
			expr := ast.NewValueExpr(yyS[yypt-0].ident)
			parser.yyVAL.expr = expr
		}
	case 75:
		{
			valExpr := yyS[yypt-1].expr.(ast.ValueExpr)
			strLit := valExpr.GetString()
			expr := ast.NewValueExpr(strLit + yyS[yypt-0].ident)
			// Fix #4239, use first string literal as projection name.
			if valExpr.GetProjectionOffset() >= 0 {
				expr.SetProjectionOffset(valExpr.GetProjectionOffset())
			} else {
				expr.SetProjectionOffset(len(strLit))
			}
			parser.yyVAL.expr = expr
		}
	case 80:
		{
			parser.yyVAL.item = true
		}
	case 81:
		{
			parser.yyVAL.item = false
		}
	case 82:
		{
			parser.yyVAL.item = true
		}
	case 83:
		{
			parser.yyVAL.item = false
		}
	case 84:
		{
			parser.yyVAL.item = opcode.GE
		}
	case 85:
		{
			parser.yyVAL.item = opcode.GT
		}
	case 86:
		{
			parser.yyVAL.item = opcode.LE
		}
	case 87:
		{
			parser.yyVAL.item = opcode.LT
		}
	case 88:
		{
			parser.yyVAL.item = opcode.NE
		}
	case 89:
		{
			parser.yyVAL.item = opcode.NE
		}
	case 90:
		{
			parser.yyVAL.item = opcode.EQ
		}
	case 91:
		{
			parser.yyVAL.item = opcode.NullEQ
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, parser.yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
