name: Test
on: [push, pull_request]
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build & Test
      run: make dev
